version: "3.8"

services:
  backend:
    build: .
    image: khannnar/spam-classifier-backend:1.0.0
    ports:
      - "9000:9000"  # Flask API
    volumes:
      - ./mlflow:/mlflow
    networks:
      - spam-classification-network

  frontend:
    build: ./spam-classifier-fe
    image: khannnar/spam-classifier-frontend:1.0.0
    ports:
      - "3000:80" 
    depends_on:
      - backend
    networks:
      - spam-classification-network

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000
    depends_on:
      - backend
      - frontend
    networks:
      - spam-classification-network

networks:
  spam-classification-network:
    driver: bridge
